# Generated by Django 4.0.5 on 2022-06-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year_of_public', models.DateField()),
                ('genre', models.CharField(max_length=120)),
                ('isAvaliable', models.BooleanField()),
                ('author', models.ManyToManyField(to='MyLibrary.myauthor')),
                ('takenBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyLibrary.myuser')),
            ],
        ),
    ]
